config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('corpus.urls')),
    path('standard/', include('standard.urls')),
    path('history/', include('history.urls')),
    path('admin/', admin.site.urls),
]

corpus/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'corpus'
urlpatterns = [
    path('', DocumentList.as_view(), name='index'),
    path('<int:pk>/', DocumentDetail.as_view(), name='detail'),
    path('create/', DocumentCreate.as_view(), name='create'),
    path('update/<int:pk>/', DocumentUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', DocumentDelete.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

history/urls.py
from django.urls import path, include
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'history'
urlpatterns = [
    path('', HistoryFormView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

standard/urls.py
from django.urls import path, include
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'standard'
urlpatterns = [
    path('', StandardFormView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

corpus/models.py
from django.db import models


class Document(models.Model):
    title = models.CharField(max_length=120, null=False)
    author = models.CharField(max_length=20, null=False)
    file = models.FileField(upload_to='text/')
    STATUS_CODE = [
        (0, '신규'),
        (1, '보류'),
        (2, '완료')
    ]
    status = models.IntegerField(default=0, choices=STATUS_CODE, auto_created=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id} / {self.title} / {self.author}'

history/models.py
from django.db import models

# Create your models here.

class History(models.Model):
    word = models.CharField(max_length=120, null=False)
    original = models.CharField(max_length=120, null=True, blank=True)
    alias = models.CharField(max_length=120, null=True, blank=True)
    keyword = models.CharField(max_length=120, null=True, blank=True)
    area = models.CharField(max_length=120, null=True, blank=True)
    type = models.CharField(max_length=120, null=True, blank=True)
    time = models.CharField (max_length=120, null=True, blank=True)
    url = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.word

standard/models.py
from django.db import models

# Create your models here.

class Standard(models.Model):
    word = models.CharField(max_length=120, null=False)
    original = models.CharField(max_length=120, null=False)
    definition = models.TextField()

    def __str__(self):
        return self.word

corpus/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['title', 'author', 'file']
        def __init__(self, *args, **kwargs):
            super(DocumentForm, self).__init__(*args, **kwargs)
            for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'

history/forms.py
from django import forms

class HistoryForm(forms.Form):
    search_word = forms.CharField(label='검색어')

    def __init__(self, *args, **kwargs):
        super(HistoryForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

standard/forms.py
from django import forms

class StandardForm(forms.Form):
    search_word = forms.CharField(label='검색어')

    def __init__(self, *args, **kwargs):
        super(StandardForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

corpus/views.py
from .models import Document
from .forms import DocumentForm

from django.views import generic
from django.urls import reverse_lazy

class DocumentList(generic.ListView):
    model = Document
    ordering = ['id']


class DocumentCreate(generic.CreateView):
    model = Document
    form_class = DocumentForm
    success_url = reverse_lazy('corpus:index')


class DocumentDetail(generic.DetailView):
    model = Document


class DocumentUpdate(generic.UpdateView):
    model = Document
    fields = ['title', 'author', 'file', 'status']
    success_url = reverse_lazy('corpus:index')


class DocumentDelete(generic.DeleteView):
    model = Document
    success_url = reverse_lazy('corpus:index')

history/views.py
from django.views.generic import FormView
from django.shortcuts import render
from django.db.models import Q

from .forms import HistoryForm
from .models import History

class HistoryFormView(FormView):
    form_class = HistoryForm
    template_name = 'history/history_list.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        word_list = History.objects.filter(Q(word__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = word_list

        return render(self.request, self.template_name, context)

standard/views.py
from django.views.generic import ListView, FormView
from django.db.models import Q
from django.shortcuts import  render

from .models import Standard
from .forms import StandardForm

class StandardFormView(FormView):
    form_class = StandardForm
    template_name = 'standard/standard_list.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        word_list = Standard.objects.filter(Q(word__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = word_list

        return render(self.request, self.template_name, context)

corpus/templates/corpus/document_confirm_delete.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST">
        {%csrf_token%}
        {{object}}를 삭제할까요?
        <input type="submit" value="삭제">
    </form>
</body>
</html>

corpus/templates/corpus/document_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %} 문서 상세보기 {% endblock %}

{% block content %}


<!-- 페이지별 제목-->
<header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
    <div class="container-xl px-4">
        <div class="page-header-content pt-4">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto mt-4">
                    <h1 class="page-header-title">
                        <div class="page-header-icon"><i data-feather="upload"></i></div>
                        문서명 - {{object.title}}
                    </h1>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container-xl px-4 mt-n10">
    <div class="card card-waves">
        <div class="card-header">문서 선택하기</div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="저장">
                <input type="reset" value="취소">
            </form>
        </div>
    </div>
</div>
{% endblock %}

corpus/templates/corpus/document_form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}문서 목록 {% endblock %}

{% block content %}


<!-- 페이지별 제목-->
<header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
    <div class="container-xl px-4">
        <div class="page-header-content pt-4">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto mt-4">
                    <h1 class="page-header-title">
                        <div class="page-header-icon"><i data-feather="upload"></i></div>
                        문서 수정
                    </h1>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container-xl px-4 mt-n10">
    <div class="card card-waves">
        <div class="card-header"> 파일명 - {{ object.title }}</div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="저장">
                <input type="reset" value="취소">
            </form>
        </div>
    </div>
</div>
{% endblock %}

corpus/templates/corpus/document_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}문서 목록 {% endblock %}

{% block content %}
<!-- 페이지별 제목-->
<header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
    <div class="container-xl px-4">
        <div class="page-header-content pt-4">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto mt-4">
                    <h1 class="page-header-title">
                        <div class="page-header-icon"><i data-feather="list"></i></div>
                        문서 목록
                    </h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main page content-->
<div class="container-xl px-4 mt-n10">
    <div class="card mb-4">
        <div class="card-header">문서 추가</div>
        <div class="card-body text-center">
            <h5>현재는 텍스트 파일(.txt)만 추가할 수 있습니다.</h5>
            <a class="btn btn-outline-primary" href="{% url 'corpus:create' %}" role="button">문서 추가하기</a>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header">문서 확인</div>
        <div class="card-body">

            <table id="datatablesSimple">
                <thead>
                <tr>
                    <th class="text-center">순번</th>
                    <th class="text-center">제목</th>
                    <th class="text-center">등록자</th>
                    <th class="text-center">등록일</th>
                    <th class="text-center">상태</th>
                    <th class="text-center">작업</th>
                </tr>
                </thead>
                <tbody>
                {% if object_list %}
                {% for each in object_list %}
                <tr>
                    <td class="text-center">{{each.id}}</td>
                    <td class="text-center">{{each.title}}</td>
                    <td class="text-center">{{each.author}}</td>
                    <td class="text-center">{{each.created_at | date:'Y-m-d'}}</td>
                    <td class="text-center">
                        {% if each.status == 0 %}
                        <div class="badge bg-primary text-white rounded-pill">{{each.get_status_display}}</div>
                        {% elif each.status == 1 %}
                        <div class="badge bg-warning text-white rounded-pill">{{each.get_status_display}}</div>
                        {% else %}
                        <div class="badge bg-info text-white rounded-pill">{{each.get_status_display}}</div>
                        {% endif %}
                    </td>
                    <td class="text-center">
                        <a class="btn btn-datatable btn-icon btn-transparent-dark" href="/{{ each.id }}"
                           role="button">
                            <i data-feather="search"></i>
                        </a>
                        <a class="btn btn-datatable btn-icon btn-transparent-dark"
                           href="{% url 'corpus:update' each.id %}"
                           role="button">
                            <i data-feather="edit"></i>
                        </a>
                        <a class="btn btn-datatable btn-icon btn-transparent-dark "
                           data-bs-target="#deleteModal{{each.id}}" data-bs-toggle="modal"
                           role="button">
                            <i data-feather="trash-2"></i>
                        </a>
                        <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade"
                             id="deleteModal{{each.id}}"
                             role="dialog"
                             tabindex="-1">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">파일명 - {{ each.title }}</h5>
                                        <button aria-label="Close" class="btn-close" data-bs-dismiss="modal"
                                                type="button"></button>
                                    </div>
                                    <div class="modal-body">이 문서를 삭제하시겠습니까?</div>
                                    <div class="modal-footer">
                                        <button class="btn btn-secondary" data-bs-dismiss="modal" type="button">아니오
                                        </button>
                                        <button class="btn btn-primary" type="button">예</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

history/templates/history/history_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}한국민족문화대백과사전{% endblock %}

{% block content %}
<!-- 페이지별 제목-->
<header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
    <div class="container-xl px-4">
        <div class="page-header-content pt-4">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto mt-4">
                    <h1 class="page-header-title">
                        <div class="page-header-icon"><i data-feather="list"></i></div>
                        한국민족문화대백과사전
                    </h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main page content-->
<div class="container-xl px-4 mt-n10">
    <div class="card mb-4">
        <div class="card-header">검색하기</div>
        <div class="card-body">
            <form action="." method="post">
                {% csrf_token %}
                <div class="col-xxl-4 col-xl-6 mb-4 align-self-center">
                {{ form.search_word }}
                </div>
                <input class="btn btn-primary btn-sm" type="submit" value="Submit">
            </form>
        </div>
    </div>
    {% if search_term %}
    <div class="card mb-4">
        <div class="card-header">검색결과: {{ search_term }}</div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                <tr>
                    <th class="text-center">순번</th>
                    <th class="text-center">단어</th>
                    <th class="text-center">원어</th>
                </tr>
                </thead>
                <tbody>
                {% if object_list %}
                {% for each in object_list %}
                <tr>
                    <td class="text-center">{{each.id}}</td>
                    <td class="text-center">{{each.word}}</td>
                    <td class="text-center">{{each.original}}</td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

standard/templates/standard/standard_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}표준국어대사전{% endblock %}

{% block content %}
<!-- 페이지별 제목-->
<header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
    <div class="container-xl px-4">
        <div class="page-header-content pt-4">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto mt-4">
                    <h1 class="page-header-title">
                        <div class="page-header-icon"><i data-feather="list"></i></div>
                        표준국어대사전
                    </h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main page content-->
<div class="container-xl px-4 mt-n10">
    <div class="card mb-4">
        <div class="card-header">검색하기</div>
        <div class="card-body">
            <form action="." method="post">
                {% csrf_token %}
                <div class="col-xxl-4 col-xl-6 mb-4 align-self-center">
                {{ form.search_word }}
                </div>
                <input class="btn btn-primary btn-sm" type="submit" value="Submit">
            </form>
        </div>
    </div>
    {% if search_term %}
    <div class="card mb-4">
        <div class="card-header">검색결과: {{ search_term }}</div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                <tr>
                    <th class="text-center">순번</th>
                    <th class="text-center">단어</th>
                    <th class="text-center">원어</th>
                </tr>
                </thead>
                <tbody>
                {% if object_list %}
                {% for each in object_list %}
                <tr>
                    <td class="text-center">{{each.id}}</td>
                    <td class="text-center">{{each.word}}</td>
                    <td class="text-center">{{each.original}}</td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="kr">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}사전 구축 시스템{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>
    <link href="{% static 'sb-admin/css/styles.css' %}" rel="stylesheet"/>
    <link rel="icon" type="image/x-icon" href="{% static 'sb-admin/assets/img/favicon.png' %}"/>
    <script data-search-pseudo-elements defer
            src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js"
            crossorigin="anonymous"></script>
    {% block extra-style %}{% endblock %}
</head>
<body class="nav-fixed">
<nav class="topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white"
     id="sidenavAccordion">
    <!-- Sidenav Toggle Button-->
    <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 me-2 ms-lg-2 me-lg-0" id="sidebarToggle"><i
            data-feather="menu"></i></button>
    <a class="navbar-brand pe-3 ps-4 ps-lg-2" href="#">사전 구축 시스템</a>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sidenav shadow-right sidenav-light">
            <div class="sidenav-menu">
                <div class="nav">
                    <div class="sidenav-menu-heading">메뉴</div>
                    <a class="nav-link" href="/">
                        <div class="nav-link-icon">
                            <i data-feather="search"></i>
                        </div>
                        말뭉치 관리
                    </a>
                    <a class="nav-link" href="/history">
                        <div class="nav-link-icon">
                            <i data-feather="book"></i>
                        </div>
                        한국민족문화대백과사전
                    </a>
                    <a class="nav-link" href="/standard">
                        <div class="nav-link-icon">
                            <i data-feather="book"></i>
                        </div>
                        표준국어대사전(역사분야)
                    </a>
                </div>
            </div>
            <!-- Sidenav Footer-->
            <div class="sidenav-footer">
                <div class="sidenav-footer-content">
                    <div class="sidenav-footer-subtitle">Logged in as:</div>
                    <div class="sidenav-footer-title">Valerie Luna</div>
                </div>
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <footer class="footer-admin mt-auto footer-light">
            <div class="container-xl px-4">
                <div class="row">
                    <div class="col-md-6 small">Copyright &copy; Your Website 2021</div>
                    <div class="col-md-6 text-md-end small">
                        <a href="#!">Privacy Policy</a>
                        &middot;
                        <a href="#!">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'sb-admin/js/scripts.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="{% static 'sb-admin/js/datatables/datatables-simple-demo.js' %}"></script>
{% block extra-script %}{% endblock %}
</body>
</html>